title: Joanne Liao
author: GitHub User
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  åœ¨ä¸€å€‹æœ‰è¶£çš„å¤§å­¸å°±è®€çš„æ•¸å­¸ç³»studentğŸ‘©â€ğŸ“ï¼Œæ²’ä»€éº¼ç‰¹åˆ¥çš„æ‰èƒ½ï¼Œéå¸¸çš„å¹³å‡¡ç„¡å¥‡ï¼Œå”¯ä¸€ç‰¹åˆ¥çš„å¤§æ¦‚æ˜¯å¹´é½¡ç¨é•·é€™é»ï¼Œéå¸¸çš„å¹³å‡¡ç„¡å¥‡ï¼Œå”¯ä¸€ç‰¹åˆ¥çš„å¤§æ¦‚æ˜¯å¹´é½¡ç¨é•·é€™é»ğŸ˜³ã€‚å–œæ­¡çœ‹é›»è¦–ã€é›»å½±ğŸ¬ï¼Œä¹Ÿå–œæ­¡å¶çˆ¾ç©ç©é›»è…¦ğŸ‘©â€ğŸ’»ã€‚

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: joanneliao # your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-tactile
